### PR TITLE
fix build on macosx

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
Homebrew/homebrew#41312

**Comment by phako** [comment]
Is the fix stil needed? Also, in general the usual way of contributing to this project is by posting patches on GNOME's bugzilla

**Comment by ilovezfs** [comment]
@phako Yes this is still needed. Even with 0.20.17:

```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -D_REENTRANT -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libsoup/2.52.2_1/include/libsoup-2.4 -I/usr/local/Cellar/gssdp/0.14.15/include/gssdp-1.0 -I/usr/include/libxml2 -I.. -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Wno-error=unused-parameter -Wno-error=missing-field-initializers -c gupnp-marshal.c  -fno-common -DPIC -o .libs/gupnp-marshal.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -D_REENTRANT -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libsoup/2.52.2_1/include/libsoup-2.4 -I/usr/local/Cellar/gssdp/0.14.15/include/gssdp-1.0 -I/usr/include/libxml2 -I.. -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Wno-error=unused-parameter -Wno-error=missing-field-initializers -c xml-util.c -o xml-util.o >/dev/null 2>&1
guul.c:25:13: fatal error: 'uuid.h' file not found
#   include <uuid.h>
            ^
1 error generated.
make[2]: *** [guul.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -D_REENTRANT -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libsoup/2.52.2_1/include/libsoup-2.4 -I/usr/local/Cellar/gssdp/0.14.15/include/gssdp-1.0 -I/usr/include/libxml2 -I.. -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Wno-error=unused-parameter -Wno-error=missing-field-initializers -c gupnp-marshal.c -o gupnp-marshal.o >/dev/null 2>&1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
==> Formula
```

**Comment by phako** [comment]
Sorry, slightly too late for today's release. Patch pushed to master. Please close this PR, I cannot.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to gupnp!

gupnp uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
